package assets

// assetManagerGenerated is an AssetManager with implementation based on
// generated by go-bindata functions.
type assetManagerGenerated struct{}

// NewManagerGenerated creates AssetManager based on generated by
// go-bindata functions.
func NewManagerGenerated() AssetManager {
	return assetManagerGenerated{}
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func (am assetManagerGenerated) Asset(name string) ([]byte, error) {
	return Asset(name)
}

// AssetNames returns the names of the assets.
func (am assetManagerGenerated) AssetNames() []string {
	return AssetNames()
}
